### ISSUE TITLE
Not supporting on virtuals

### ISSUE THREAD

**Issue by RevealedSoulEven** [BryanGIG/KMrite#4]
Actually it's working fine on Virtual Environments like Vphonegaga/VMOS

But it would be better if it could support Virtuals available on Play Store.

Similar to like Gameguardian Supports virtuals like parallel space, Dualspace and others. So if could get support to those virtuals too it would be great as the Virtual Environments like vmos consume too much data,space and memory and isn't more effecient like those virtuals that GG supports.

**Comment by RevealedSoulEven** [comment]
Also I've checked it's not working on some root virtual environments like F1VM and some VMOS roms

I got to see that this is because the /proc/[pid]/ folder is empty there

I prefer you to use SuFile and SuRandomAccessFile from libsu and make some changes to make it work

**Comment by RevealedSoulEven** [comment]
I further investigated it and came to know that the remotemessenger under testServive() in MainActivity.kt is giving the error.
The remotemessenger is getting nulled. I wonder how it's working everywhere else but some devices doesn't support it.

Any way we can fix it?

**Comment by BryanGIG** [comment]
> I prefer you to use SuFile and SuRandomAccessFile from libsu and make some changes to make it work

If you're using it with `Root permission`, than the app will create **service** with root access.
So any method that call from the service will had full root access, and calling `SuFile` will be result the same result as `File`

**Comment by BryanGIG** [comment]
> I further investigated it and came to know that the remotemessenger under testServive() in MainActivity.kt is giving the error. The remotemessenger is getting nulled. I wonder how it's working everywhere else but some devices doesn't support it.
> 
> Any way we can fix it?

Please provide some logs

**Comment by RevealedSoulEven** [comment]
> 

Actually log isn't showing in that vmos rom but I saw that in older devices and F1VM also it's not working...
That remotemessenger value is null there I saw using if else

Can you please skip that part or make the project in complete java so that it would be easy to copy the codes and use them directly in our main class instead of using remotemessenger

**Comment by BryanGIG** [comment]
> Actually log isn't showing in that vmos rom but I saw that in older devices and F1VM also it's not working...
> That remotemessenger value is null there I saw using if else

If that the case, [fda3547](https://github.com/BryanGIG/KMrite/commit/fda3547dd5680b54add19b70e8593dd21e522d72) should fix this issue

**Comment by RevealedSoulEven** [comment]
Still the same.
![Screenshot_2022-04-17-08-56-50-949_com f1player](https://user-images.githubusercontent.com/49313374/163699006-09ecb1b4-a750-4c94-a520-e3c06c40152e.jpg)

As you can see it's stuck after printing "Result : " and again and again when I click the button it does the same @BryanGIG can you please give your telegram ir discord or something where we can together give our time to fix it

**Comment by RevealedSoulEven** [comment]
I got that the rootservices has a problem.
But why?

**Comment by BryanGIG** [comment]
Ah it seems like i mention the wrong commit.
Pease try the latest commit and inform me

**Comment by RevealedSoulEven** [comment]
I tried the latest one and still no chance. It's not working too🥲🥲

**Comment by RevealedSoulEven** [comment]
I thought to forget everyhting and create a new java file using SuFile and SuRandomAccessFile because that's all required to read that memory and all.

I spent whole day now and end up at a hilarious situation.

I somehow managed to get the lib.so starting address as well as the pid and I'm using SuRandomAcessFile to write the hex. But I don't know why is my code isn't working.

`public static void memEdit(int offset, String hex) {
        SuRandomAccessFile raf = null;
        {
            try {
                raf = SuRandomAccessFile.open(new SuFile("/proc/"+pid+"/mem"),"rw");
            } catch (FileNotFoundException e) {
                e.printStackTrace();
                Log.i(TAG, "memEdit: not found");
            }
        }
        try
        {
            raf.seek((sAddress+offset));
            raf.write(Hex2b(hex));
            return;
        }
        catch (IOException paramString1)
        {
            paramString1.printStackTrace();
        }
}`

I can easily get that sAddress i.e. the lib.so starting address and also I can read that memory using raf.seek() and raf.readbytes()

But I don;t know why isn't thay raf.write working in my phone even in my original device.

Any idea or any guess I can do? I'll share a new version of KMrite in Java after that!

**Comment by RevealedSoulEven** [comment]
@BryanGIG  can you please write that memEdit part in Java and send me. I'll complete my project. But I need that using Superuser commands like SuRandomAccessFile or any as I'm not using Root Services

**Comment by BryanGIG** [comment]
Im missing the point of this issue.

**Comment by RevealedSoulEven** [comment]
ok then can you fix the rootservices?
